wayfair/brickkit-ios

README.md

* Added a build badge
* whitespace trimming from my editor

Added travis build badge

---

README.md

Added Carthage install in README.md

---

Source/Behaviors/SpotlightLayoutBehavior.swift

Fix spotlight layout behavior bug

---

Source/ViewControllers/BrickCollectionView.swift

Removed incorrect information in deprecation statement

---

Source/Bricks/Button/ButtonBrick.swift
Source/Bricks/Collection/CollectionBrick.swift
Source/Bricks/Image/ImageBrick.swift
Source/Bricks/Label/LabelBrick.swift
Source/Cells/BrickCell.swift
Source/Models/BrickDimension.swift
Source/Models/BrickModels.swift
Source/ViewControllers/BrickCollectionView+BrickLayoutDataSource.swift
Tests/Cells/AsynchronousResizableCellTests.swift
Tests/Interactive/InteractiveTests.swift
Tests/Models/BrickModelsTests.swift
Tests/ViewControllers/BrickCollectionViewTests.swift
Tests/ViewControllers/BrickViewControllerTests.swift

Combines bricks width and height into one pram on init

Added Brick Size

---

Source/Models/BrickDimension.swift

BrickSize public init

---

Source/Behaviors/StickyLayoutBehavior.swift
Tests/Behaviors/StickyLayoutBehaviorTests.swift

Fixed sticking percentage for stacking sticky bricks

---

Example/BrickKit-Example.xcodeproj/project.pbxproj
Example/Source/Examples/Interactive/ActivityIndicatorOverrideSource.swift
Example/Source/Examples/Interactive/DynamicContentViewController.swift
Source/Bricks/Image/ImageBrick.swift
Source/Cells/BrickCell.swift
Source/Models/BrickModels.swift
Tests/Bricks/LabelBrickTests.swift

- provides a means of showing placeholder content

Provide a way to override brick cell content after the updateContent

---

Source/ViewControllers/BrickCollectionView.swift
Source/ViewControllers/BrickViewController.swift
Tests/ViewControllers/BrickCollectionViewTests.swift

I added the ability to change the default nib when the brick class is registered.

Added changing the default nib

---

Source/Bricks/Image/ImageBrick.swift
Source/Cells/ImageDownloader.swift
Tests/Bricks/ImageBrickTests.swift

Add function to ImageDownloader protocol

---

Source/Bricks/Generic/GenericBrick.swift
Tests/Bricks/GenericBrickTests.swift

Moved place where generic brick background color is set to clear

---

Resources/iOS/Bricks/Image/ImageBrick.xib
Resources/tvOS/Bricks/Image/ImageBrick.xib
Source/Bricks/Image/ImageBrick.swift

Incorporate a callback to determine when the image brick sets its own image

Fixed generic brick

---

Source/Layout/BrickFlowLayout.swift
Source/Layout/BrickLayoutInvalidationContext.swift
Tests/Layout/BrickInvalidationContextTests.swift

Set the correct contentOffsetAdjustment on height change when invalidating the layout
Fixes #84

contentOffsetAdjustment on height change

---

Source/Models/BrickDimension.swift

I fixed this leak ![brickkit leak](https://cloud.githubusercontent.com/assets/4155467/24725020/57866170-1a1b-11e7-9011-57c225595119.png)

Fixed memory leak with BrickDimension

---

Source/Models/BrickModels.swift
Tests/ViewControllers/BrickCollectionViewTests.swift

Support for repeatCount on Brick-level

---

BrickKit.xcodeproj/project.pbxproj
BrickKit.xcworkspace/contents.xcworkspacedata
Example/Playgrounds/BrickRepeatCountPlayground.playground/contents.xcplayground
Example/Playgrounds/Brickkit Playground.playground/Pages/BrickRepeatCount.xcplaygroundpage/Contents.swift
Example/Playgrounds/Brickkit Playground.playground/Pages/LabelBrick.xcplaygroundpage/Contents.swift
Example/Playgrounds/Brickkit Playground.playground/contents.xcplayground
Example/Playgrounds/LabelBrickPlayground.playground/contents.xcplayground
Tests/Bricks/ImageBrickTests.swift

Moved playgrounds to pages and checked App Extension API only setting

---

.travis.yml
Tests/Bricks/ImageBrickTests.swift

Closes #145. Updated all simulators to 10.3, and added Xcode 11 target.

Update travis to run iOS 11 tests

---

BrickKit.xcodeproj/project.pbxproj
Source/Bricks/Generic/GenericBrick.swift
Source/Cells/BrickCell.swift
Tests/Cells/FrameCalculationTests.swift
Tests/Cells/FrameInfoBrick.swift
Tests/Cells/nibs/iOS/FrameInfoBrick.xib
Tests/Cells/nibs/tvOS/FrameInfoBrick.xib

On layoutSubviews, the cell will now verify if the width of the frame is equal to the expected width. If so, `framesDidLayout` will be called. This way, the brick can get informed that the frames are set correctly and images etc can be fetched.
Fixes #161

BrickCell width provider

---

Example/BrickKit-Example.xcodeproj/xcshareddata/xcschemes/BrickApp-iOS.xcscheme
Example/Source/Examples/Interactive/InvalidateHeightViewController.swift
Source/Cells/BrickCell.swift
Source/Layout/BrickFlowLayout.swift
Source/ViewControllers/BrickCollectionView+BrickLayoutDataSource.swift
Source/ViewControllers/BrickCollectionView.swift
Tests/Bricks/LabelBrickTests.swift
Tests/ViewControllers/BrickCollectionViewTests.swift

Fixed the invalidating heights animation

---

BrickKit.xcodeproj/project.pbxproj
Example/BrickKit-Example.xcodeproj/project.pbxproj
Example/Playgrounds/Brickkit Playground.playground/Pages/Restricted Brick Sizes.xcplaygroundpage/Contents.swift
Example/Playgrounds/Brickkit Playground.playground/contents.xcplayground
Example/Source/Examples/Simple/RestrictedBrickViewController.swift
Example/Source/Navigation/NavigationDataSource.swift
Source/Cells/BrickCell.swift
Source/Models/BrickDimension.swift
Source/ViewControllers/BrickCollectionView.swift
Tests/Cells/DummyResizableBrick.swift
Tests/Cells/nibs/iOS/DummyResizableBrick.xib
Tests/Cells/nibs/tvOS/DummyResizableBrick.xib
Tests/Layout/RestrictedBrickSizeTest.swift

Created a way for bricks to be restricted with a minimum size or maximum size

Added Restricted Brick Size

---

BrickKit.xcodeproj/project.pbxproj
Source/Cells/BrickCell.swift
Source/Layout/BrickFlowLayout.swift
Source/Layout/BrickLayoutInvalidationContext.swift
Source/Layout/BrickLayoutSection.swift
Source/Utils/BrickLogger.swift
Source/Utils/BrickUtils.swift
Source/ViewControllers/BrickCollectionView.swift
Tests/Behaviors/StickyFooterLayoutBehaviorTests.swift
Tests/Bricks/ButtonBrickTests.swift
Tests/Bricks/CollectionBrickTests.swift
Tests/Bricks/ImageBrickTests.swift
Tests/Bricks/LabelBrickTests.swift
Tests/Cells/AsynchronousResizableCellTests.swift
Tests/Layout/BrickFlowLayoutSectionTests.swift
Tests/Layout/BrickFlowLayoutTests.swift
Tests/Layout/BrickLayoutSectionTests.swift
Tests/Utils/BrickLoggerTests.swift
Tests/Utils/XCTests.swift
Tests/ViewControllers/BrickCollectionViewTests.swift

- Fixed performance of height recalculation
- Added logging
Fixes #63

Fixed performance of height recalculation

---

Source/Cells/BrickCell.swift

Reverts wayfair/brickkit-ios#184

Added update edgeInsets logic

---

Source/Bricks/Collection/CollectionBrick.swift
Tests/Bricks/CollectionBrickTests.swift

Add delegate to collection brick that notifies when section was set for safe manipulation of the brickCollectionView

CollectionBrickCellDelegate addition

---

Example/Source/Bricks/Custom/HeaderAndFooterBrick.swift
Source/Bricks/Button/ButtonBrick.swift
Source/Bricks/Image/ImageBrick.swift
Source/Bricks/Label/LabelBrick.swift
Source/Layout/BrickLayout.swift
Source/Models/Brick.swift
Source/ViewControllers/BrickCollectionView.swift
Tests/Bricks/ButtonBrickTests.swift

Addressed backwards compatible warnings surfaced by Xcode 10 beta 5
