wayfair/brickkit-ios

Source/Behaviors/SpotlightLayoutBehavior.swift
Tests/Behaviors/SpotlightLayoutBehaviorTests.swift

Because `attributesDidUpdate` wasn’t called, the `BrickZones` weren’t updated. This resulted in `layoutAttributesForElementsInRect` returning the wrong data
Fixes #4

SpotlightLayoutBehavior now calls `attributesDidUpdate`

---

Source/Models/BrickDimension.swift

Use UIScreen.mainScreen's traitCollection instead of UIView.  UIView is not on view hierarchy at time of call, so the trait collections are all unspecified.  This messes up sizing for bricks on iPad.
This commit fixes issue #6

Fix BrickDimension for iPad.

---

Example/Source/Examples/BaseBrickController.swift
Example/Source/Examples/Sticking/StickingFooterBaseViewController.swift
Source/Behaviors/StickyFooterLayoutBehavior.swift
Source/Layout/BrickFlowLayout.swift
Source/Layout/BrickLayout.swift
Source/Layout/BrickLayoutSection.swift
Tests/Behaviors/StickyFooterLayoutBehaviorTests.swift

- StickyFooterLayoutBehavior was still using `frame` instead of `originalFrame` for the calculations
- BrickLayoutSection also needs to take previously calculated bricks into account if the origin had already changed
- Fixed Demo App when enabling/disabling behaviors
- Test
Fixes #8

Sticky footer was wrongly calculated

---

.travis.yml
BrickKit.xcodeproj/project.pbxproj
Source/Models/BrickDimension.swift
Tests/Models/BrickDimensionTests.swift
Tests/Utils/Swizzle.swift

- Check for orientation is now done on `UIScreen.mainScreen().bounds`
- Added tests that swizzle `UIScreen.mainScreen()`
Fixes #13

BrickDimension now checks on UIScreen bounds

---

Source/ViewControllers/BrickCollectionView.swift
Tests/Bricks/CollectionBrickTests.swift

The `updateHeight` call is now wrapped in a `performBatchUpdates`, so the UI will always be updated
Fixes #15

Wrapped `updateHeight` in `performBatchUpdates`

---

Source/Layout/BrickLayoutSection.swift
Tests/Layout/BrickInvalidationContextTests.swift

When an attribute gets updated because a height, it will also update the whole row, so the heights are aligned.
When doing so, the attributes that were updated, were not properly registered, hence never filled into the `invalidatedItemIndexPaths` array. This caused the collectionView NOT to update that attribute.
This is fixed by registering those attributes as well
Fixes #17

Reported changed attributes correctly

---

Source/Bricks/Collection/CollectionBrick.swift
Tests/Bricks/CollectionBrickTests.swift

If the CollectionBrick has bricks with heights that are calculated using AutoLayout, the `sizeChangedHandler` was called during layoutSubviews, which caused a reload but the height wasn’t yet calculated
Fixed by adding a flag that indicates if the CollectionBrick is currently calculating the layout
Fixes #28

Fixed reloading of CollectionBricks

---

Example/Source/Examples/Interactive/InvalidateHeightViewController.swift
Source/Layout/BrickLayoutSection.swift
Tests/ViewControllers/BrickCollectionViewTests.swift

The algoritm to check the max Y of a row was not taking in account an `invalidation`
Fixes #36

Fixed wrong contentSize when Brick’s height changed

---

Docs/BRICK_DIMENSION.md
Example/BrickKit-Example.xcodeproj/project.pbxproj
Example/Source/Examples/Simple/FillBrickViewController.swift
Example/Source/Examples/Simple/SimpleBrickViewController.swift
Example/Source/Navigation/NavigationDataSource.swift
Source/Layout/BrickFlowLayout.swift
Source/Layout/BrickLayout.swift
Source/Layout/BrickLayoutSection.swift
Source/Models/BrickDimension.swift
Source/ViewControllers/BrickCollectionView+BrickLayoutDataSource.swift
Tests/Models/BrickDimensionTests.swift
Tests/Utils/DataSources.swift
Tests/ViewControllers/BrickCollectionViewTests.swift

A Remainder BrickDimension will have a width that is the remainder that is left on a row
Fixes #39

Support for “Remainder” BrickDimension

---

Example/Source/Examples/HorizontalScroll/HorizontalCollectionViewController.swift
Example/Source/Examples/Simple/SimpleRepeatBrickViewController.swift
Example/Source/Examples/Sticking/StickingFooterSectionsViewController.swift
Example/Source/Examples/Sticking/StickingSectionsViewController.swift
Source/Layout/BrickFlowLayout.swift
Source/Layout/BrickLayout.swift
Source/Layout/BrickLayoutSection.swift
Source/Models/BrickModels.swift
Source/ViewControllers/BrickCollectionView+BrickLayoutDataSource.swift
Tests/Layout/AlignRowHeightTests.swift
Tests/Layout/BrickInvalidationContextTests.swift
Tests/Layout/LazyLoadingTests.swift
Tests/Utils/DataSources.swift
Tests/ViewControllers/BrickCollectionViewTests.swift

The alignRowHeights property is now set per BrickSection instead of on the whole BrickLayout
Fixes #41

alignRowHeights per BrickSection

---

Source/Layout/BrickLayoutSection.swift
Tests/Interactive/InteractiveTests.swift

InvalidateRepeatCounts now ensures the identifiers of the BrickAttributes to be correct
Fixes #50

InvalidateRepeatCounts + identifiers

---

BrickKit.xcodeproj/project.pbxproj
Source/Bricks/Generic/GenericBrick.swift
Source/Cells/BrickCell.swift
Source/Models/BrickModels.swift
Source/ViewControllers/BrickCollectionView.swift
Source/ViewControllers/BrickViewController.swift
Tests/Bricks/GenericBrickTests.swift
Tests/Utils/XCTests.swift

Introduction of a GenericBrick, that allows to wrap any UIView in a Brick.
This will allow a straight forward syntax:
```
GenericBrick<UILabel>(GenericLabelBrickIdentifier, size: BrickSize(...)) { label, cell in
label.text = "LABEL " + String(cell.index)
cell.edgeInsets = UIEdgeInsets(top: 5, left: 10, bottom: 15, right: 20)
}
```
Fixes #64

GenericBrick

---

Example/Source/Examples/Interactive/InteractiveAlignViewController.swift
Example/Source/Examples/Simple/AlignmentBrickViewController.swift
Example/Source/Examples/Simple/SimpleRepeatFixedWidthViewController.swift
Source/Layout/BrickLayout.swift
Source/Layout/BrickLayoutSection.swift
Source/Models/BrickAlignment.swift
Source/Models/BrickModels.swift
Source/ViewControllers/BrickCollectionView+BrickLayoutDataSource.swift
Tests/Models/BrickAlignmentTests.swift
Tests/Utils/DataSources.swift

- Changed BrickAlignment from an `enum` to a `struct` that holds vertical and horizontal alignment
- Introduced `BrickHorizontalAlignment` enum
- Introduced `BrickVerticalAlignment` enum
- Tests
Fixes #69

Horizontal and Vertical BrickAlignment

---

Source/Bricks/Button/ButtonBrick.swift
Tests/Bricks/ButtonBrickTests.swift

Added action to the UIButton when loaded through GenericBrick<UIButton>
Fixes #75

Fixed ButtonBrick by adding action to UIButton

---

Source/Layout/BrickLayoutSection.swift
Tests/Layout/BrickFlowLayoutTests.swift

Added precision when analyzing if a brick should be put on the next row
CGFloat can be very precise, which could lead to a difference of `-1.13686837721616e-13` between two values, that are actually the same. This is now fixed by adding in a precision accuracy of `0.0000001`
Fixes #77

Optimized brick calculation

---

Source/Models/BrickModels.swift
Source/ViewControllers/BrickCollectionView.swift
Tests/Utils/XCTests.swift
Tests/ViewControllers/BrickCollectionViewTests.swift
Tests/ViewControllers/BrickViewControllerTests.swift

You can now set `nibIdentifiers` to a BrickSection, so you don’t have to register Bricks upfront anymore
Fixes #90

Add `nibIdentifiers` to the BrickSection

---

Example/BrickKit-Example.xcodeproj/project.pbxproj
Example/Source/Examples/Interactive/IsHiddenBrickViewController.swift
Example/Source/Navigation/NavigationDataSource.swift
Source/Layout/BrickFlowLayout.swift
Source/Layout/BrickLayout.swift
Source/Layout/BrickLayoutInvalidationContext.swift
Source/Models/BrickModels.swift
Source/ViewControllers/BrickCollectionView+BrickLayoutDataSource.swift
Tests/Behaviors/HideLayoutBehaviorTests.swift
Tests/Layout/BrickInvalidationContextTests.swift

Introduces the `isHidden` property on the `Brick`-class. This way, there is not always a need for a `hideBehaviorDataSource` if this is wanted. After the flag is changed, the `invalidateVisibility` still needs to be called on the `BrickCollectionView`
Fixes #93

isHidden property on Brick

---

Source/Layout/BrickLayoutSection.swift

customHeightProvider allowed update heights of bricks that aren’t estimated yet. This doesn’t work well with scrolling from bottom to top
Fixes #97

Removed customHeightProvider

---

Source/Bricks/Image/ImageBrick.swift
Source/Cells/BrickCell.swift
Source/Layout/BrickLayoutSection.swift
Source/Models/BrickDimension.swift
Source/ViewControllers/BrickCollectionView+BrickLayoutDataSource.swift
Tests/Interactive/InteractiveTests.swift
Tests/Layout/BrickInvalidationContextTests.swift
Tests/Models/BrickDimensionTests.swift

This issue came along when invalidating a repeat count of a section with multiple bricks. The logic assumed that the repeat count was set for simular bricks and only for appending. This fix will now check if the attributes have the same identifiers. And if not, the invalidation of the cells will start with the first attribute that has a different identifier
Fixes #101

Fixed invalidateRepeatCounts

---

Source/ViewControllers/BrickCollectionView.swift
Tests/Cells/AsynchronousResizableBrick.swift
Tests/ViewControllers/BrickCollectionViewTests.swift

Previously, the sizeChangedHandler callback set on resizable cells in BrickCollectionView was accidentally capturing a collection cell reference from outside the closure and causing a retain cycle, even though the cell was passed into the closure as an argument. This change resolves that issue so that the argument is referenced instead of any captured variables.
This also includes a test to ensure that the collection cell is deallocated properly if the brick collection view that owns it is also deallocated. I needed to make a new test async cell since the existing one uses an NSTimer which interferes with the deinitialization in ways I don't fully understand.
I recommend releasing a new version of BrickKit as soon as this is merged since this can leak a lot of memory, especially if the …

Fix severe memory leak when using async resizable cells

---

Source/Layout/BrickLayoutSection.swift
Tests/Layout/BrickLayoutSectionTests.swift
Tests/ViewControllers/BrickViewControllerTests.swift

When recalculating the origin of a section, the origin of the sectionAttributes weren’t set upfront
Fixes #104

SectionAttributes weren’t updated

---

Source/Cells/BrickCell.swift
Tests/Behaviors/CoverFlowLayoutBehaviorTests.swift

before returning the preferred layout attributes. This line broke cover flow and was causing stack overflows in some cases.

Removed a line that modified an attribute’s height

---

Source/Bricks/Collection/CollectionBrick.swift
Tests/Bricks/CollectionBrickTests.swift
Tests/Cells/AsynchronousResizableCellTests.swift

This is an issue when you have an outer collection brick with a fixed height, and an inner collection brick with an automatic height.  When scrolling the outer collection brick, the inner collection brick will keep resizing itself because the outer collection brick is also resizing itself.  This merge makes it so that if a collection brick has a fixed height, it will not try to resize itself.
Fixes #109

Collection bricks with fixed heights were infinitely resizing.

---

Source/Bricks/Collection/CollectionBrick.swift
Tests/Bricks/CollectionBrickTests.swift
Tests/Cells/AsynchronousResizableCellTests.swift

This is an issue when you have an outer collection brick with a fixed height, and an inner collection brick with an automatic height. When scrolling the outer collection brick, the inner collection brick will keep resizing itself because the outer collection brick is also resizing itself. This merge makes it so that if a collection brick has a fixed height, it will not try to resize itself.
Fixes #109

Collection bricks with a fixed height would infinitely resize.

---

Tests/Behaviors/CoverFlowLayoutBehaviorTests.swift

The line of code that this fix deletes is not present in the Swift 3 branch, so only the test is included here.

Added a test for the preferred layout attributes height

---

BrickKit.xcworkspace/contents.xcworkspacedata
Example/Playgrounds/BrickRepeatCountPlayground.playground/Contents.swift
Example/Playgrounds/BrickRepeatCountPlayground.playground/contents.xcplayground
Example/Playgrounds/LabelBrickPlayground.playground/Contents.swift
Example/Playgrounds/LabelBrickPlayground.playground/contents.xcplayground
README.md

Playground examples

---

Source/ViewControllers/BrickCollectionView.swift

This should fix the occasional error `UICollectionView was deallocated while an update was in flight`. I tried writing unit tests around this but couldn't force the crash to trigger.

Preventing self from deallocating during performPatchUpdates.

---

Example/Source/Examples/Layout/SizeClassesBrickViewController.swift
Source/Bricks/Collection/CollectionBrick.swift
Source/Bricks/Image/ImageBrick.swift
Source/Cells/BrickCell.swift
Source/Models/BrickDimension.swift
Source/ViewControllers/BrickCollectionView+BrickLayoutDataSource.swift
Tests/Models/BrickDimensionTests.swift

Allows the BrickKit collection view controller to apply different dimensions based upon how wide the brick is. Starting with a minimum dimension that would be applicable to all widths, the app can the specify different dimensions for any additional widths.
100% code coverage for all additional code.
Added code to sample app to demonstrate support for it.

Varadic range support

---

Example/BrickKit-Example.xcodeproj/project.pbxproj
Example/Source/Examples/BaseBrickController.swift
Example/Source/Examples/Collections/HorizontalScrollSectionBrickViewController.swift
Example/Source/Examples/Collections/RepeatCollectionBrickViewController.swift
Example/Source/Examples/HorizontalScroll/BlockHorizontalViewController.swift
Example/Source/Examples/HorizontalScroll/HorizontalCollectionViewController.swift
Example/Source/Examples/Images/ImagesInCollectionBrickHorizontalViewController.swift
Example/Source/Examples/Images/ImagesInCollectionBrickViewController.swift
Example/Source/Examples/Simple/ReverseBrickViewController.swift
Example/Source/Examples/Simple/SimpleBrickViewController.swift
Example/Source/Navigation/NavigationDataSource.swift
Source/Bricks/Collection/CollectionBrick.swift
Source/Layout/BrickLayoutInvalidationContext.swift
Tests/Bricks/CollectionBrickTests.swift
Tests/Layout/BrickInvalidationContextTests.swift

- Cleanup the sample app. Mainly update protocols that changed function signatures, but had a default implementation, so the compiler didn’t complain
- Fixed a weird behavior when bricks would disappear when the estimated height of a brick was much bigger than the actual brick. This is solved by setting the `invalidateItems` to nil, so the collectionView will fetch the layoutAttributes again
Fixes #142

Cleanup Sample App + Fixed “disapearing bricks”

---

Source/Bricks/Generic/GenericBrick.swift
Tests/Bricks/GenericBrickTests.swift

GenericBrick’s updateContent would clear the background colors. This caused a problem when reloading a cell with the actual reload via UICollectionView
Fixes #154

GenericBrick background color won’t reset to clear

---

Example/Source/Examples/Interactive/InsertBrickViewController.swift
Source/Layout/BrickAppearBehavior.swift
Source/Layout/BrickFlowLayout.swift
Source/ViewControllers/BrickCollectionView.swift
Tests/Layout/BrickAppearBehaviorTests.swift
Tests/ViewControllers/BrickCollectionViewTests.swift

Items can now be inserted and deleted from anywhere in the brickCollectionView and the collectionView will be responsive to the change.

Inserting/deleting items from middle of a brickCollectionView

---

Example/Source/Bricks/Custom/SegmentHeaderBrick.swift
Example/Source/Examples/Interactive/BrickCollectionInteractiveViewController.swift
Example/Source/Examples/Interactive/DynamicContentViewController.swift
Example/Source/Examples/Interactive/InteractiveAlignViewController.swift
Source/Cells/BrickCell.swift
Source/Layout/BrickFlowLayout.swift
Source/Layout/BrickLayoutInvalidationContext.swift
Source/Layout/BrickLayoutSection.swift
Tests/Layout/BrickLayoutSectionTests.swift

The items that are inserted/deleted will now be properly placed in the correct atttributes location, so that the animations make much more sense
Fixes #158

Properly insert/delete items

---

Source/Cells/BrickCell.swift
Source/ViewControllers/BrickCollectionView.swift
Tests/Bricks/GenericBrickTests.swift
Tests/ViewControllers/BrickCollectionViewTests.swift

Searching for indexPaths could cause a lot of calculations. To find indexPaths for a given index, BrickKit will now first check the visible cells. If it can’t find it, it will continue to use the old, slower way
Fixes #152

Optimize indexPath search using visible cells

---

Source/Bricks/Image/ImageBrick.swift
Source/Cells/BrickCell.swift
Source/Cells/ImageDownloader.swift
Tests/Bricks/ImageBrickTests.swift
Tests/Cells/FrameInfoBrick.swift

This fixes a run-time crash during dequeing a cell while brick hasn’t yet been set.  Checks if it’s an AsynchronouseResizableCell before calling layoutIfNeeded during the attribute pass.

Checks if _brick!=nil before calling framesDidLayout().

---

Source/Bricks/Image/ImageBrick.swift
Tests/Bricks/ImageBrickTests.swift

This fixes a bug that causes an image brick cell to not properly reset before reusing it.

Image view now shows the correct image when the cell is reused

---

Source/Cells/BrickCell.swift

The conditional that checked whether `edgeInsets == oldValue` caused brickCells to update its edgeInsets incorrectly when the cell's edgeInset was set. When the edgeInset is set sometimes the insets would change to the desired values but sometimes the inset would change to the default value. The deleted code was intended for performance purposes so it does not break the current code.

Removed code that caused edgeInsets to update incorrectly

---

Source/Models/BrickSection.swift
Source/ViewControllers/BrickCollectionView.swift
Tests/ViewControllers/BrickViewControllerTests.swift

Adds a dictionary field to brick section so that we are able to register a class for a given identifier if we do not a brick to be reused across the class. This is something that can be used when we use a lot of different label bricks.

Use Identifiers to register bricks and be able to register cell classes

---

Source/Layout/BrickFlowLayout.swift

This fixes issue where scrolling in a carousel that used collection brick caused cells above to re-size to a smaller size than what was already calculated

Revert change in PR #164

---

Source/Behaviors/BrickLayoutBehavior.swift
Source/Behaviors/CardLayoutBehavior.swift
Source/Behaviors/OffsetLayoutBehavior.swift
Source/Behaviors/SpotlightLayoutBehavior.swift
Source/Behaviors/StickyLayoutBehavior.swift
Source/Bricks/Generic/GenericBrick.swift
Source/Layout/BrickFlowLayout.swift
Source/Layout/BrickLayoutSection.swift
Source/Models/BrickDimension.swift
Tests/Behaviors/CardLayoutBehaviorTests.swift
Tests/Behaviors/CoverFlowLayoutBehaviorTests.swift
Tests/Behaviors/MaxZIndexBehaviorTests.swift
Tests/Behaviors/MinimumStickyLayoutBehaviorTests.swift
Tests/Behaviors/OffsetLayoutBehaviorTests.swift
Tests/Behaviors/SetZIndexBehaviorTests.swift
Tests/Behaviors/SpotlightLayoutBehaviorTests.swift
Tests/Bricks/GenericBrickTests.swift
Tests/Models/BrickDimensionTests.swift
Tests/Utils/DataSources.swift

Added perfromance improvements by:
- Better checking for context invalidation. If certain behaviors are added to a layout but there are no index paths that would need invalidation by the behaviors, the context shouldn't invalidate.
- Removing excessive sorting when creating BrickRangeDimensions (dimension pairs now have to be provided in minimum size order) 
- Adding a custom height provider for generic brick cells. This will be helpful for generic brick cells that want to use its own size computation rather than rely on auto layout.

Performance Improvements

---

Source/Bricks/Generic/GenericBrick.swift
Tests/Bricks/GenericBrickTests.swift

Allows for more flexibility in specifying a custom height. Also happens to fix a potential memory leak.

Updated height provider code to be a closure

---

Source/Bricks/Button/ButtonBrick.swift
Source/Bricks/Label/LabelBrick.swift
Tests/Bricks/ButtonBrickTests.swift
Tests/Bricks/LabelBrickTests.swift

Added prepareForReuse functions to Button and Label bricks

---

Source/Bricks/Button/ButtonBrick.swift
Source/Bricks/Label/LabelBrick.swift
Tests/Bricks/ButtonBrickTests.swift
Tests/Bricks/LabelBrickTests.swift

Slight change to the `prepareForReuse` functions for `LabelBrick` and `ButtonBrick`. The background colors should default to .clear instead of .white.

Background colors should default to .clear not .white.

---

Source/Bricks/Generic/GenericBrick.swift
Tests/Cells/FrameCalculationTests.swift

This will allow the function to access _brick.index and cell.genericContentView, which can be used to make content changes later in the layout cycle, convenient when loading images based on the size of the UIImageView.

Updated the UpdateFrameListener function to pass the GenericBrickCell.

---

BrickKit.xcodeproj/project.pbxproj
Source/Cells/BrickCell.swift
Source/Layout/BrickFlowLayout.swift
Source/Layout/BrickLayoutSection.swift
Source/ViewControllers/BrickCollectionView.swift
Tests/ViewControllers/BrickViewControllerTests.swift

- Includes a fix (and unit tests) for the crashes that occur due to changing repeat counts. @rubencagnie has looked at this change and agreed it looks good.
- Add the flag needsLegacyEdgeInsetFunctionality to BrickCell, which defaults to false, but can be set to true if the legacy handling of edge insets is required.
- Remove some forced unwraps in BrickFlowLayout to avoid crashes.
- Fix a crash that could occur due to calculating layouts of deleted sections in BrickFlowLayout.
- Refactor Height provider to be a closure instead of protocol.
- Fix a crash due to unchecked bounds of a range creation in BrickLayoutSection
- Clear prefetch index paths upon invalidation.
- Add additional verbose logging to refresh/reloading of data.
--------------
Squashed Commit of the following:
commit …

Stability, Layout, and Logging Enhancements; Added Support for Legacy Edge Insets Functionality

---

.travis.yml
BrickKit.xcodeproj/project.pbxproj
Example/BrickKit-Example.xcodeproj/project.pbxproj
Example/Source/Examples/Interactive/InsertBrickViewController.swift
Example/Source/Examples/Simple/ReorderableBrickViewController.swift
Example/Source/Theme.swift
README.md
Source/Bricks/Collection/CollectionBrick.swift
Source/Bricks/Generic/GenericBrick.swift
Source/Cells/BrickCell.swift
Tests/Behaviors/CoverFlowLayoutBehaviorTests.swift
Tests/Behaviors/SpotlightLayoutBehaviorTests.swift
Tests/Bricks/GenericBrickTests.swift
Tests/Bricks/ImageBrickTests.swift
Tests/Bricks/LabelBrickTests.swift
Tests/Layout/BrickFlowLayoutTests.swift
Tests/Layout/LazyLoadingTests.swift
Tests/Utils/XCTests.swift
Tests/ViewControllers/BrickCollectionViewTests.swift
Tests/ViewControllers/BrickViewControllerTests.swift

Migrated to swift 4.0
closes #198

Migrated to Swift 4

---

Source/Cells/BrickCell.swift

This fixes an issue found with the GenericBrickCell in which the first time the genericContentView is the incorrect size.  This forces the genericContentView to resize.

Call layoutIfNeeded on the cell’s contentView instead of just cell

---

Example/Source/Examples/Interactive/InteractiveAlignViewController.swift

Fixes #209. This was somehow not caught in Swift 3 migration.

#209: Fixed outdated didSelectItemAt signature in interactive align example
